# Generated by Django 3.2 on 2022-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0002_questions_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
