# Generated by Django 3.2 on 2022-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0005_alter_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='no_view',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='no_view',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
