# Generated by Django 3.2 on 2022-05-18 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resourcebank', '0006_auto_20220513_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='no_view',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='no_view',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='rating',
        ),
        migrations.CreateModel(
            name='Question_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_on', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('no_of_views', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcebank.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question_Rating',
                'verbose_name_plural': 'Question_Ratings',
                'ordering': ['pk'],
            },
        ),
    ]
