# Generated by Django 3.2 on 2022-05-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0010_auto_20220518_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='answer_attachment/'),
        ),
    ]
