# Generated by Django 3.2 on 2022-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0011_answers_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='answer_attachment/%Y/%m/%d'),
        ),
    ]
