# Generated by Django 3.2 on 2022-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0016_alter_answers_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('add_file', models.FileField(blank=True, null=True, upload_to='answer_attachment')),
            ],
            options={
                'verbose_name': 'Testsave',
                'verbose_name_plural': 'Testsave',
                'ordering': ['pk'],
            },
        ),
    ]
