# Generated by Django 3.2 on 2022-05-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0018_alter_testsave_add_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='attachment',
        ),
    ]
