# Generated by Django 3.2 on 2022-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0020_answers_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('add_file', models.FileField(blank=True, null=True, upload_to='material_upload/')),
            ],
            options={
                'verbose_name': 'UploadFile',
                'verbose_name_plural': 'UploadFiles',
                'ordering': ['pk'],
            },
        ),
    ]
