# Generated by Django 3.2 on 2022-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcebank', '0023_alter_uploadfile_add_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='question_attachment'),
        ),
    ]
